.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809
  
stages:
  - build
  - test
  
before_script:
 - Set-Variable -Name "time" -Value (date -Format "%H:%m")
 - echo "job ${CI_JOB_NAME} started by ${GITLAB_USER_NAME} at ${time}"
 
build:upstream_release:
  extends:
  - .shared_windows_runners
  stage: build
  interruptible: true
  script:
  - echo "running scripts in the build job"
  - .\Build-PsadtPlus.ps1
  artifacts:
    paths:
     - PSADTPlus*.zip
    expire_in: 1 week

build:upstream_gitmaster:
  extends:
  - .shared_windows_runners
  stage: build
  interruptible: true
  script:
  - echo "running scripts in the build job"
  - .\Build-PsadtPlus.ps1
  artifacts:
    paths:
     - PSADTPlus*.zip
    expire_in: 1 week    
  
test:
  extends:
  - .shared_windows_runners
  stage: test
  script:
  - echo "running scripts in the test job"