.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809
  
stages:
  - build
  - test
  
before_script:
 - Set-Variable -Name "time" -Value (date -Format "%H:%m")
 - echo ${time}
 - echo "started by ${GITLAB_USER_NAME}"
 
build:upstream_release:
  extends:
  - .shared_windows_runners
  stage: build
  interruptible: true
  script:
  - echo "running scripts in the build job"
  - .\Build-PsadtPlus.ps1
  artifacts:
    paths:
     - PSADTPlus*.zip
    expire_in: 1 week

build:upsteam_gitmaster:
  extends:
  - .shared_windows_runners
  stage: build
  interruptible: true
  script:
  - echo "running scripts in the build job"
  - .\Build-PsadtPlus.ps1
  artifacts:
    paths:
     - PSADTPlus*.zip
    expire_in: 1 week    
  
test:
  extends:
  - .shared_windows_runners
  stage: test
  script:
  - echo "running scripts in the test job"