name: Build-PSADTPlus
on: push

jobs:

  buildfromrelease:
    name: Build PSADT-Plus from PSADT Releases
    runs-on: windows-latest
    env:
      build_type: release
    steps:
      - name: Checkout PSADT-Plus repository
        uses: actions/checkout@v2
      - name: Build with PSADT newest release
        shell: pwsh
        run: pwsh -command ".\$GITHUB_WORKSPACE\Build-PsadtPlus.ps1"
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: psadtplus-release
          path: PSADTPlus*.zip  

  buildfrommaster:
    name: Build PSADT-Plus from PSADT master git branch
    runs-on: windows-latest
    env:
      build_type: master
    steps:
      - name: Checkout PSADT-Plus repository
        uses: actions/checkout@v2
      - name: Build with PSADT current master branch
        shell: pwsh
        run: pwsh -command ".\$GITHUB_WORKSPACE\Build-PsadtPlus.ps1"
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: psadtplus-master
          path: PSADTPlus*.zip
